### ISSUE TITLE
[Question] Mesh password

### ISSUE THREAD

**Issue by TomixUG** [Leiaz/python-awox-mesh-light#14]
Is there some way to get password from the app? I captured packets with Bluetooth HCI snoop log in Android dev options. 

Btw thanks for this library it works great.

EDIT 1: I cant set mesh password. It throws this error: 
```
Connected.
Receiced notification from characteristic 00010203-0405-0607-0809-0a0b0c0d1912
Received message : b'\xd6\xd9~\x00\x00\x963\xdc`\x01X\x80\x03\x7f\x7fd\xff\x00\x00\x00'
Mesh network settings change failed : bytearray(b'\x0e')
Disconnecting.
```
Code: 
```
import awoxmeshlight
import logging

logger = logging.getLogger("awoxmeshlight")
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler ()
handler.setLevel(logging.DEBUG)
logger.addHandler (handler)

light = awoxmeshlight.AwoxMeshLight ("A4:C1:38:44:06:58") 
light.connect()
light.setMesh("PixtxaLightNet", "IeY3johvoosh","4556572782865925") 
light.disconnect()
```
Light doesnt do anything after that

EDIT 2: I just fixed it by changing setMesh name, pass and key: `light.setMesh("mesh_name", "mesh_pwd", "mesh_key")`

**Comment by Leiaz** [comment]
> Is there some way to get password from the app? 

Someone [captured network communication](https://github.com/Leiaz/python-awox-mesh-light/issues/3#issuecomment-370616938) but I'm not a fan of installing proprietary apps that says "contains ads" to install SSL certificate and try to MITM other apps connections.
If you have access to complete developer options on your phone for instance with adb root, you can try looking in the app's /data folder.

**Comment by guirem** [comment]
Maybe a working answer there : https://github.com/Leiaz/python-awox-mesh-light/issues/3#issuecomment-579193617

**Comment by TomixUG** [comment]
> Maybe a working answer there : [#3 (comment)](https://github.com/Leiaz/python-awox-mesh-light/issues/3#issuecomment-579193617)
Ok I will try it thanks

**Comment by TomixUG** [comment]
> Maybe a working answer there : [#3 (comment)](https://github.com/Leiaz/python-awox-mesh-light/issues/3#issuecomment-579193617)

Thanks, it worked! Sorry for a "little" late reply.
